# ============================================
# Base de données (choisir UN seul bloc)
# ============================================

# --- TOI : Neon Cloud ---
# spring.datasource.url=jdbc:postgresql://ep-morning-dew-am4lumpj-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
# spring.datasource.username=neondb_owner
# spring.datasource.password=npg_qMi93GZrfTPa

# --- EQUIPE : Localhost ---
spring.datasource.url=jdbc:postgresql://localhost:5432/dbminikindergarten
spring.datasource.username=postgres
spring.datasource.password=maycem
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
