# ============================================
# Base de données (choisir UN seul bloc)
# ============================================

# --- TOI : Neon Cloud ---
# spring.datasource.url=jdbc:postgresql://ep-morning-dew-am4lumpj-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
# spring.datasource.username=neondb_owner
# spring.datasource.password=npg_qMi93GZrfTPa

# --- EQUIPE : Localhost ---
spring.datasource.url=jdbc:postgresql://localhost:5432/dbminikindergarten
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / Hibernate
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ============================================
# Erreur
# ============================================
server.error.whitelabel.enabled=false

# ============================================
# Mail (Mailtrap)
# ============================================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=d5ccd7f8856fa9
spring.mail.password=baa30750d24304
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
